version: "3.8"

services:
  app:
    image: slr-frontend_prod
    ports: 
      - 1000:80
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    environment:
      - backend=2000
    restart: on-failure